//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Product:InotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductReceipts = new HashSet<ProductReceipt>();
        }
        private int id;
        private string name;
        private int? barcode;
        private string category;
        private string producer;

        public int ID 
        { 
            get => id; set
            {
                id=value;
                OnPropertyChanged(nameof(ID));
            }

        }

        public string Name
        {
            get => name; set
            {
                name = value;
                OnPropertyChanged(nameof(Name));
            }
        }

        public int? Barcode
        {
            get => barcode; set
            {
                barcode = value;
                OnPropertyChanged(nameof(Barcode));
            }
        }

        public string Category
        {
            get => category; set
            {
                category = value;
                OnPropertyChanged(nameof(Category));
            }
        }

        public string Producer
        {
            get => producer; set
            {
                producer = value;
                OnPropertyChanged(nameof(Producer));
            }
        }

        public virtual Category Category1 { get; set; }
        public virtual Producer Producer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReceipt> ProductReceipts { get; set; }
        public virtual Stock Stock { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
