//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReceipt
    {
        public int prod_id { get; set; }
        public int receipt_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> subtotal { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
